[package]
name = "partiql-rs"
version = "0.202105.8"
edition = "2018"
description = "A implementation of PartiQL"
homepage = "https://github.com/fuyutarow/partiql-rs"
repository = "https://github.com/fuyutarow/partiql-rs.git"
authors = ["FUKUDA Yutaro <fuyutarow@gmail.com>"]
license = "MIT"
readme = "README.md"
categories = ["database", "parsing", "parser-implementations"]
keywords = ["partiql"]

[lib]
name = "partiql"
path = "src/lib/mod.rs"

[[bin]]
name = "partiql-cli"
path = "src/bin/main.rs"

[dependencies]
anyhow = "1.0.40"
itertools = "0.10.0"
nom = "6.1.2"
regex = "1.5.4"
serde = "1.0.126"
serde_derive = "1.0.126"
serde_json = "1.0.64"
serde_partiql = "1.0.64+20210523"
structopt = "0.3.21"
