[package]
name = "partiql-rs"
version = "0.202105.3"
edition = "2018"

[lib]
name = "partiql"
path = "src/lib/mod.rs"

[[bin]]
name = "partiql-cli"
path = "src/bin/main.rs"

[dependencies]
anyhow = "1.0.40"
nom = "6.1.2"
regex = "1.5.4"
serde = "1.0.126"
serde_derive = "1.0.126"
serde_json = "1.0.64"
serde_partiql = { git = "https://github.com/fuyutarow/serde-partiql" }
structopt = "0.3.21"
