[tasks.release-cli]
script = '''
cargo build --release --bin partiql-cli
'''

[tasks.version-up]
script = '''
version-make up -rz Cargo.toml
'''

[tasks.version-tag]
script = '''
git tag v$(version-make show Cargo.toml)
'''

[tasks.fix]
script = '''
cargo fix
'''
