[tasks.hot]
dependencies = ["build:pq"]
script = '''
zx tests/pq/poke.mjs
'''

[tasks.install-dev]
script = '''
brew install jq jo yj
brew install fuyutarow/tap/tests-make
'''

[tasks."build:pq"]
command = "cargo"
args = ["build", "--bin", "pq"]

[tasks.release]
command = "cargo"
args = ["build", "--release"]

[tasks."release:pq"]
command = "cargo"
args = ["build", "--bin", "pq", "--release"]

# not working
[tasks."test:all"]
run_task = [{ name = "test:lib" }, { name = "test:pq" }]

[tasks."test:lib"]
command = "cargo"
args = ["test"]
dependencies = ["build"]

[tasks."test:pq"]
dependencies = ["build:pq"]
script = '''
tests-make tests-make.toml
'''

[tasks.up]
script = '''
git remote add upstream https://github.com/fuyutarow/partiql-rs
git fetch upstream
git merge upstream/alpha
'''

[tasks.version-up]
script = '''
version-make up -rz Cargo.toml
'''

[tasks.version-tag]
script = '''
git tag v$(version-make show Cargo.toml)
'''

[tasks.version-untag]
script = '''
git tag v$(version-make show Cargo.toml) -d
'''

[tasks.fix]
script = '''
cargo fix
'''


[tasks.generate-json]
dependencies = ["build"]
script = '''
alias pc="./target/debug/partiql-cli"
alias pq="./target/debug/pq"
for i in $(seq 1 18)
do
    cat samples/q$i.env | pc from --to json | pq -S > samples/q$i.json
done
'''
