[tasks."add:submodules"]
script = '''
git submodule update --init
'''

[tasks."install:dev"]
script = '''
brew install jq jo yj
brew install fuyutarow/tap/tests-make
brew install fuyutarow/tap/version-make
cargo install cargo-distribute
npm i -g markdown-to-document ;: use mdtodoc for publish:README
'''

[tasks."release:readme"]
# GitHub Flavored Markdown (GFM) does not support footnotes. So use `mdtodoc` to convert markdown to html.
script = '''
mdtodoc _readme/README.md -e light
'''

[tasks.pq]
script = '''
cargo run --bin pq --features cli --
'''

[tasks."build:all"]
script = '''
makers build:pq
makers build:py
makers build:js
'''

[tasks."build:pq"]
args = ["build", "--bin", "pq", "--features", "cli table"]
command = "cargo"

[tasks."build:js"]
script = '''
cd piqel-js
makers build:js
'''

[tasks."install:dev:py"]
script = '''
cd piqel-py
makers update:py
'''

[tasks."build:py"]
script = '''
cd piqel-py
makers build:py
'''

[tasks.release]
args = ["build", "--release"]
command = "cargo"

[tasks."release:pq"]
args = ["build", "--bin", "pq", "--release", "--features", "cli table"]
command = "cargo"

[tasks."release:js"]
script = '''
cd piqel-js
makers release:js
'''

[tasks."publish:rs"]
dependencies = ["release"]
script = '''
cargo publish
'''

[tasks."publish:js"]
script = '''
cd piqel-js
makers publish:js
'''

[tasks."publish:py"]
script = '''
cd piqel-py
makers publish:py
'''

[tasks.cov]
script = '''
cargo kcov
'''

[tasks.lint]
script = '''
cargo fix --allow-dirty
cargo fmt
'''

[tasks.test]
alias = "test:all"

[tasks."test:all"]
script = '''
makers test:lib
makers test:pq
makers test:py
'''

[tasks."test:lib"]
args = ["test"]
command = "cargo"
dependencies = ["build"]

[tasks."test:pq"]
dependencies = ["build:pq"]
script = '''
tests-make tests-make/index.toml
'''

[tasks."test:pqrs"]
dependencies = ["build:pq"]
script = '''
makers test:lib
makers test:pq
'''

[tasks."test:py"]
script = '''
cd piqel-py
makers test:py
'''

[tasks."web:dev"]
script = '''
cd examples/next
npm run dev
'''

[tasks."web:prod"]
script = '''
cd examples/next
npm run up:partiql
npm run prod
'''

[tasks."test:web"]
script = '''
tests-make tests-make/web.toml
'''

[tasks."dist:up"]
script = '''
cargo-distribute --tap ~/homebrew-tap/ --bin pq --features "cli table" --channel nightly
'''

[tasks.up]
script = '''
git remote add upstream https://github.com/fuyutarow/piqel
git fetch upstream
git merge upstream/alpha
'''

[tasks."version:up"]
script = '''
version-make up -rz Cargo.toml
version-make up -rz piqel-js/Cargo.toml
version-make up -rz piqel-py/Cargo.toml
# version-make set piqel-js/Cargo.toml -v "$(version-make show Cargo.toml)" -r
'''

[tasks."version:tag"]
script = '''
git tag v$(version-make show Cargo.toml)
'''

[tasks."version:untag"]
script = '''
git tag v$(version-make show Cargo.toml) -d
'''

[tasks.generate-json]
dependencies = ["build"]
script = '''
alias pc="./target/debug/partiql-cli"
alias pq="./target/debug/pq"
for i in $(seq 1 18)
cat samples/q$i.env | pc from --to json | pq -S > samples/q$i.json
'''

[tasks."doc:start"]
script = '''
cd docs
yarn
yarn start
'''
