[tasks."add:py"]
dependencies = ["build:py"]
script = '''
poetry run maturin develop
'''

[tasks."build:py"]
script = '''
poetry run maturin build
'''

[tasks."test:py"]
dependencies = ["add:py"]
script = '''
poetry run pytest
'''

[tasks."shell:py"]
script = '''
poetry run python
'''

[tasks."release:py"]
script = '''
poetrun run maturin build --release
'''

[tasks."publish:py"]
dependencies = ["release:py"]
script = '''
poetrun run maturin publish
'''
