[tool.poetry]
name = "partiql-tests"
version = "0.1.0"
description = ""
authors = ["fuyutarow <fuyutarow@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
maturin = "^0.10.6"

[tool.maturin]
bindings = "cffi"
manylinux = "off"
