[env]
INPUT = '''
{
  "no": 1,
  "name": "Bulbasaur",
  "types": [
    "Grass",
    "Poison"
  ],
  "height": 0.70,
  "weight": 6.9
}
'''

[tests.to-json]
script = '''
echo $INPUT | ./target/debug/pq -t json
'''
tobe = '''
{
  "no": 1,
  "name": "Bulbasaur",
  "types": [
    "Grass",
    "Poison"
  ],
  "height": 0.7,
  "weight": 6.9
}
'''

[tests.to-json-compact]
script = '''
echo $INPUT | ./target/debug/pq -t json -c
'''
tobe = '''
{"no":1,"name":"Bulbasaur","types":["Grass","Poison"],"height":0.7,"weight":6.9}
'''


[tests.to-toml]
script = '''
echo $INPUT | ./target/debug/pq -t toml
'''
tobe = '''
no = 1
name = 'Bulbasaur'
types = [
    'Grass',
    'Poison',
]
height = 0.7
weight = 6.9

'''

[tests.to-yaml]
script = '''
echo $INPUT | ./target/debug/pq -t yaml
'''
tobe = '''
"no": 1
name: Bulbasaur
types:
  - Grass
  - Poison
height: 0.7
weight: 6.9

'''

[tests.to-xml]
script = '''
echo $INPUT | ./target/debug/pq -t xml
'''
tobe = '''
<no>1</no><name>Bulbasaur</name><types>GrassPoison</types><height>0.7</height><weight>6.9</weight>
'''


[tests.to-partiql]
script = '''
echo $INPUT | ./target/debug/pq -t partiql
'''
tobe = '''
{
  "no": 1,
  "name": "Bulbasaur",
  "types": <<
    "Grass",
    "Poison"
  >>,
  "height": 0.7,
  "weight": 6.9
}
'''
