[env]
INPUT = '''
{
  "name": "Mew",
  "id": 151,
  "fleeRate": 0.1
}
'''

[tests.to-json]
script = '''
alias pq ="./target/debug/pq"
echo "${INPUT}" | pq -t json
'''
tobe = '''
{
  "name": "Mew",
  "id": 151,
  "fleeRate": 0.1
}
'''

[tests.to-toml]
script = '''
alias pq ="./target/debug/pq"
echo "${INPUT}" | pq -t toml
'''
tobe = '''
name = 'Mew'
id = 151
fleeRate = 0.1

'''

[tests.to-yaml]
script = '''
alias pq ="./target/debug/pq"
echo "${INPUT}" | pq -t yaml
'''
tobe = '''
---
name: Mew
id: 151
fleeRate: 0.1

'''

[tests.to-xml]
script = '''
alias pq ="./target/debug/pq"
echo "${INPUT}" | pq -t xml
'''
tobe = '''
<name>Mew</name><id>151</id><fleeRate>0.1</fleeRate>
'''
