
[tests.BMI-top10]
script = '''
cat samples/pokemon.json/en/pokemon.json | ./target/debug/pq -q "$(cat<<EOF
SELECT no AS id, name, weight/height/height AS BMI
ORDER BY BMI DESC
LIMIT 10
EOF
)" -c
'''
tobe = '''
[{"id":76,"name":"Golem","BMI":153.06122448979593},{"id":913,"name":"Dugtrio-1","BMI":135.91836734693877},{"id":918,"name":"Geodude-1","BMI":126.875},{"id":74,"name":"Geodude","BMI":125.0},{"id":111,"name":"Rhyhorn","BMI":115.0},{"id":56,"name":"Mankey","BMI":112.0},{"id":919,"name":"Graveler-1","BMI":110.0},{"id":920,"name":"Golem-1","BMI":109.34256055363322},{"id":75,"name":"Graveler","BMI":105.0},{"id":143,"name":"Snorlax","BMI":104.30839002267572}]
'''
