
[tests.BMI-top10]
script = '''
cat samples/pokemon.json | ./target/debug/pq -q "$(cat<<EOF
SELECT no AS id, name, weight/height/height AS BMI
ORDER BY BMI DESC
LIMIT 10
EOF
)" -c
'''
tobe = '''
[{"id":76,"name":"ゴローニャ","BMI":153.06122448979593},{"id":913,"name":"ダグトリオ-1","BMI":135.91836734693877},{"id":918,"name":"イシツブテ-1","BMI":126.875},{"id":74,"name":"イシツブテ","BMI":125.0},{"id":111,"name":"サイホーン","BMI":115.0},{"id":56,"name":"マンキー","BMI":112.0},{"id":919,"name":"ゴローン-1","BMI":110.0},{"id":920,"name":"ゴローニャ-1","BMI":109.34256055363322},{"id":75,"name":"ゴローン","BMI":105.0},{"id":143,"name":"カビゴン","BMI":104.30839002267572}]
'''
