
[tests.nonamed-table]
script = '''
alias pq ="./target/debug/pq"
cat<<EOS | pq -t toml
[
  {
    "id": 3,
    "name": "Bob Smith",
    "title": null
  },
  {
    "id": 6,
    "name": "Jane Smith",
    "title": "Software Eng 2"
  }
]
EOS
'''
tobe = '''
[[]]
id = 3
name = 'Bob Smith'

[[]]
id = 6
name = 'Jane Smith'
title = 'Software Eng 2'

'''


[tests.value-after-table]
script = '''
alias pq ="./target/debug/pq"
cat<<EOS | pq -t toml
{
  "name": "partiql-pokemon",
  "private": true,
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start"
  },
  "license": "MIT"
}
EOS
'''
tobe = '''
name = 'partiql-pokemon'
private = true
license = 'MIT'

[scripts]
dev = 'next'
build = 'next build'
start = 'next start'

'''
