[tasks."build:py"]
script = '''
poetry install
poetry run maturin build
'''

[tasks."install:py"]
dependencies = ["build:py"]
script = '''
poetry run maturin develop
'''

[tasks."test:py"]
dependencies = ["install:py"]
script = '''
poetry run pytest
'''

[tasks.pytest]
script = '''
poetry run pytest
'''

[tasks."shell:py"]
script = '''
poetry run python
'''

[tasks."release:py"]
script = '''
poetry run maturin build --release
'''

[tasks."publish:py"]
dependencies = ["release:py"]
script = '''
poetry run maturin publish
'''
